In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# NumPy Arrays
## GSE 524

### NumPy Arrays

The NumPy library provides the ndarray type, which I will simply call an array.

An ndarray is like a list except that all elements must be of the same type.

Also, ndarray’s can be multi-dimensional but for now, I will focus on 1-dimensional arrays.  (For example, a 2 dimensional array can be used to represent a matrix.)

ndarray has several advantages over lists

More efficient use of memory (less memory needed since all elements of the same type and also arrays can typically be stored contiguously in memory to improve access time)

Efficient operators to perform an operation on every element of an array (faster than analogous operators for lists).  For example, summing the elements of an array or adding a scalar to every element of an array will be much faster than similar operations on lists.  

First step: import numpy module (I will use the alias np for convenience)


In [4]:
import numpy as np

### Creating arrays

In [6]:
np.array([1,3,5,7,9])  #create an array given a list
np.zeros(20)  #create an array with 20 0’s  (defaults to float type)
np.zeros(20, dtype=int)  #create an array with 20 0’s  (int type)
np.ones(10) #create an array with 10 1’s
np.full(10,4) #create an array with 10 4’s
np.arange(0,10,1)  #create an array that starts at 0, ends at 10 (exclusive), and with a step of 1
#i.e. 0 1 2 3 4 5 6 7 8 9
np.linspace(0,1,5)  #create an array with 5 values evenly spaced between 0 and 1 (inclusive)


array([1, 3, 5, 7, 9])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.random.random(10) #creates an array of 10 uniformly distributed random values between 0 and 1
np.random.normal(0,1,10) #creates an array of 10 standard normally distributed random values
np.random.randint(0,100,10) #creates an array of 10 uniformly random integers between 0 and 100 (exclusive of 100)
np.random.choice(np.array([0,100,103]),10)  #create array with 10 uniform draws from the set {0,100,103} (with replacement)

array([0.69432802, 0.05578436, 0.32234024, 0.26688457, 0.07443424,
       0.21335959, 0.77497653, 0.23378547, 0.72099685, 0.89165324])

array([ 0.55451972, -0.18184204, -0.4064241 , -2.22994924, -0.4483295 ,
       -0.55792906, -1.05456289,  0.36224958,  1.4219537 ,  0.18872403])

array([40, 99, 21, 74, 93, 33, 81, 97, 35, 20])

array([100, 103, 103, 100, 100, 103,   0, 100, 103, 100])

### Pseudorandom numbers

True random numbers could potentially be generated using some physical measurement where we know the reading to be random in theory, for example taking the last 2 digits of a physical measurement.

In practice, computers generate pseudorandom numbers.

They are not actually random at all, but they meet certain properties to seem random.

Pseudorandom number generators generate a sequence of random numbers starting with a “seed”.

If you re-use the same seed, you will get the same sequence of numbers.  

This highlights the fact that the sequence is not random at all.

This is also an advantage because it allows replication of calculations.

Choosing a different seed will give a completely difference sequence.

In [9]:
np.random.seed(100)
np.random.random(10) #generates 10 random numbers between 0 and 1
np.random.random(10) #generates 10 different random numbers between 0 and 1
np.random.seed(100)
np.random.random(20) #generates the same 20 numbers again


array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

array([0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375])

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333,
       0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749,
       0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375])

### Array Indexing

Same as lists 

(plus some other features that we'll talk about later)

### concatenate function


In [12]:
x=np.arange(1,10,2)
y=np.array([101,102,103])
np.concatenate([x,y])



array([  1,   3,   5,   7,   9, 101, 102, 103])

### Vectorized Operations

An efficient way to perform an operation on every element of an array.

The standard way to do this in compiled programming languages like C or Java is looping.

Looping is slower in Python than compiled languages, and the vectorized operations discussed next have a significant speed advantage over looping.  The reason is that these vectorized ops use compiled code to do the repeated operations very quickly whereas if you write your own loop, the code is interpreted as you go.

+,- (minus), - (negate),\*, /, \*\*, //, %

Other vectorized functions: abs, np.log, np.exp

In [14]:
x=np.arange(1,10,2)
x
y=np.arange(2,11,2)
y
x+y
x+3

[x[i]+y[i] for i in range(len(x))]

%timeit x+y

%timeit [x[i]+y[i] for i in range(len(x))]


array([1, 3, 5, 7, 9])

array([ 2,  4,  6,  8, 10])

array([ 3,  7, 11, 15, 19])

array([ 4,  6,  8, 10, 12])

[3, 7, 11, 15, 19]

496 ns ± 63.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
2.96 μs ± 85.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### More vectorized functions

np.sum, np.prod, np.cumsum, np.cumprod, np.min, np.max, np.mean, np.std, np.var, np.argmin, np.argmax, np.median, np.sort

All functions above page have a corresponding function that ignores missing values (which have the value NaN or “not a number”).

For example:
np.nansum sums an array, omitting NaN values from sum



In [16]:
a=np.array([-5,20,3,1,-8,0,4,9])
a
np.sum(a)
np.cumsum(a)
np.max(a)
np.argmax(a)
np.sort(a)

np.sum([1,3,float("nan")])
np.nansum([1,3,float("nan")])



array([-5, 20,  3,  1, -8,  0,  4,  9])

24

array([-5, 15, 18, 19, 11, 11, 15, 24])

20

1

array([-8, -5,  0,  1,  3,  4,  9, 20])

nan

4.0

np.nonzero:  returns indices of all elements that are not zero 
(Note:  np.nonzero returns a tuple.  If the input array is one-dimensional, as in my examples below, then the tuple only has one element, which is an array of indices for non-zero elements.)

In [18]:
np.nonzero(a)  #returns object of type: tuple 
np.nonzero(a)[0]  #takes the first element of the tuple, which is array of indices  type(np.nonzero(a))
type(np.nonzero(a)[0])

(array([0, 1, 2, 3, 4, 6, 7], dtype=int64),)

array([0, 1, 2, 3, 4, 6, 7], dtype=int64)

numpy.ndarray

### Vectorized operations for bool

with NumPy:  <,>,<=,>=,==,!= are vectorized

In [20]:
x=np.arange(1,7,1)
x
x >=3
x <=3
x ==3
y=np.array([1,3,5,7,9,11])
x==y




array([1, 2, 3, 4, 5, 6])

array([False, False,  True,  True,  True,  True])

array([ True,  True,  True, False, False, False])

array([False, False,  True, False, False, False])

array([ True, False, False, False, False, False])

np.any takes bool array as input and returns True if at least one element is True

np.all takes bool array as input and returns True if all elements are True

np.sum if input is bool array, it sums the elements that are True (i.e. treats True as 1 and False as 0 and sums array)

np.nonzero if input is bool array, it return indicies of all elements that are True


In [22]:
np.any(x>3)
np.all(x>3)
np.sum(x>3)
np.nonzero(x>3)[0]

True

False

3

array([3, 4, 5], dtype=int64)

& is vectorized and

| is vectorized or

~ is vectorized not


In [24]:
x
y
(x>=3) & (x<=3)
(x>=3) | (x<=1)
~(x>=3)



array([1, 2, 3, 4, 5, 6])

array([ 1,  3,  5,  7,  9, 11])

array([False, False,  True, False, False, False])

array([ True, False,  True,  True,  True,  True])

array([ True,  True, False, False, False, False])

### Two additional ways to index arrays

(1) You can provide a bool array when indexing an array, to select subsets of an array that meet a condition.  The indexing array should be same length as the array


In [26]:
x=np.arange(1,7,1)
x
x[np.array([True,True,False,False,True,False])]
x[x>3]


array([1, 2, 3, 4, 5, 6])

array([1, 2, 5])

array([4, 5, 6])

(2) You can provide an integer array that specifies all indices to select (in order).  In this case, any length array is fine. 


In [28]:
x
x[np.nonzero(x>3)]
x[np.array([1,3])]
x[np.array([4,1,3])]
x[np.array([3,0,2,0,1,0,0,0])]


array([1, 2, 3, 4, 5, 6])

array([4, 5, 6])

array([2, 4])

array([5, 2, 4])

array([4, 1, 3, 1, 2, 1, 1, 1])

### Summary of indexing

Suppose x is a NumPy array

Inside the brackets after x, you can
1.  Provide a single number to reference a single value in x
2.  Provide a range of indices using :, i.e. [1:3] or [0:10:2] 
3.  Provide a bool array of same length as x to reference elements in x that correspond to True in bool array
4.  Provide an int array of any length to reference indices of x in the int array

### One More Example

Suppose z is an array of length 30 and we want to select 10 random elements

In [31]:
z=np.random.random(30)
z

ind=np.random.choice(np.arange(0,30,1),10,replace=False)  #picks 10 random numbers (without replacement) from np.arange(0,30,1)
ind

z[ind]


array([0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045,
       0.37283205, 0.00568851, 0.25242635, 0.79566251, 0.01525497,
       0.59884338, 0.60380454, 0.10514769, 0.38194344, 0.03647606,
       0.89041156, 0.98092086, 0.05994199, 0.89054594, 0.5769015 ,
       0.74247969, 0.63018394, 0.58184219, 0.02043913, 0.21002658,
       0.54468488, 0.76911517, 0.25069523, 0.28589569, 0.85239509])

array([19,  8, 24, 17,  0, 21, 14, 12,  1, 28])

array([0.5769015 , 0.79566251, 0.21002658, 0.05994199, 0.43170418,
       0.63018394, 0.03647606, 0.10514769, 0.94002982, 0.28589569])